__title__ = 'spacy-lookup'
__version__ = '0.0.2'
__summary__ = 'spaCy pipeline component for Named Entity Recognition based on dictionaries.'
__url__ = 'https://github.com/mpuig/spacy-lookup'
__author__ = 'Marc Puig'
__email__ = 'marc.puig@gmail.com'
__license__ = 'MIT'
